version: 2
jobs:
  build:
    working_directory: erlpocket
    docker:
      - image: erlang:21.1
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ checksum "rebar.lock" }}

      - run:
          name: Reset Build Cache on master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo resetting cache on master
              rm -rf _build
            fi
      - run:
          name: Install deps using apt
          command: apt-get update && apt-get -y install python3 python3-pip python3-venv
      - run:
          name: Run eunit tests
          command: rebar3 eunit
      - run:
          name: Display test coverage report
          command: rebar3 cover -v
      - run:
          name: Convert coverage report to codecov supported format
          command:  bin/covertool -cover _build/test/cover/eunit.coverdata -appname erlpocket -output cobertura.xml
      - run:
          name: Upload coverage report to Codecov
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade codecov
            codecov
      - save_cache:
          key: build-cache-{{ checksum "rebar.lock" }}
          paths:
            - _build
